fix: vendorHash for go module (#207)
First off, thank you so much for this project, I appreciate all the work you have put into this!

I follow the main branch and build with nix, and noticed that  the go module hash didn't match, so here is a fix for it.

Failing on main
```
Tonearm ❯ nix build                                                                                                                                                           main[$?⇡] via 🐹 v1.26.0 󰣇
error: hash mismatch in fixed-output derivation '/nix/store/54jqnidw4vqrf3sp2qr1fc1vgxg3m0c5-tonearm-1.3.1-go-modules.drv':
         specified: sha256-yhrtOjFr6FGktfcHBR+O9hTYWnmkdMJnCe16+o29F6Y=
            got:    sha256-/pUSUfOt5heiObZNQRlZjN1a+j9JocB43F9072pyLjw=
error: Cannot build '/nix/store/12vf81jsa1a12jadyri3bg4v0rgkf2y6-tonearm-1.3.1.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/awabrwdzikryjw64jqfv2c1ybg4h4fba-tonearm-1.3.1
error: Build failed due to failed dependency
```
Updated hash works (and the build is cached)
```
Tonearm ❯ g co fix-go-module-hash-mismatch                                                                                                                        main[$?⇡] via 🐹 v1.26.0 took 2s ❌1 󰣇
Switched to branch 'fix-go-module-hash-mismatch'
Tonearm ❯ nix build
```

Co-authored-by: Lowe Schmidt <github@loweschmidt.se>
Reviewed-on: https://codeberg.org/dergs/Tonearm/pulls/207
Co-authored-by: Lowe Schmidt <loweschmidt@noreply.codeberg.org>
Co-committed-by: Lowe Schmidt <loweschmidt@noreply.codeberg.org>